apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: 1.6.0
      sourceRef:
        kind: OCIRepository      # <-- SWITCH TO OCI REGISTRY PROTOCOL
        name: aws-lbc-oci        # <-- TARGETS THE CONTAINER ENDPOINT BELOW
        namespace: flux-system
  install:
    createNamespace: false
  values:
    clusterName: demo-eks
    region: us-east-1
