apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.12.0
      sourceRef:
        kind: OCIRepository      # <-- SWITCH TO OCI REGISTRY PROTOCOL
        name: bitnami-oci        # <-- TARGETS THE CONTAINER ENDPOINT BELOW
        namespace: flux-system
  install:
    createNamespace: false
  values:
    provider: aws
    policy: sync
    registry: txt
    txtOwnerId: demo-eks
