apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repositories.yaml
  - namespace-cert-manager.yaml
  - cert-manager.yaml
  - alb-controller.yaml
  - external-dns.yaml
  - sample-app.yaml
